# Image

image:
  repository: vishwacloudlab/gitops-nginx
  tag: v1
  pullPolicy: Always

# Deployment

replicas: 2

# Application Information

company: Vivekcloudlab
application: GitOps Demo - Ingress/Helm
environment: Development
version: v1.0.0
color: Blue
buildDate: "31-Jul-2026"

# Service

service:
  type: LoadBalancer
  port: 80

# Ingress

ingress:
  enabled: true
  className: nginx

  host: gitops-student-09.lab.local

  path: /