apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: gitops-nginx
  namespace: gitops-demo

spec:

  ingressClassName: nginx

  rules:

  - host: gitops-student-09.lab.local

    http:

      paths:

      - path: /

        pathType: Prefix

        backend:

          service:

            name: gitops-nginx

            port:

              number: 80